---
title: "Good Ship Analytics"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
    logo: favicon_48x48.png
    favicon: favicon_48x48.png
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(plotly)
library(highcharter)
library(ggplot2)
library(alphavantager)
library(knitr)
library(RCurl)
library(tidyverse)
library(lubridate)

#Alphavantage API key:  IP3TG8GBOWDEVU2S

av_api_key("IP3TG8GBOWDEVU2S")
args(av_get)
amazonDF <- av_get(symbol = "AMZN", av_fun = "TIME_SERIES_DAILY", interval = "daily")
appleDF <- av_get(symbol = "AAPL", av_fun = "TIME_SERIES_DAILY", interval = "daily")
alphabetDF <- av_get(symbol = "GOOGL", av_fun = "TIME_SERIES_DAILY", interval = "daily")

amazonDF$Company <- "Amazon"
appleDF$Company <- "Apple"
alphabetDF$Company <- "Alphabet"

combinedDF <- rbind(amazonDF,appleDF,alphabetDF)

```

Stocks
======

Column {.sidebar}
-----------------------------------------------------

### Select Stocks data to display

```{r}
selectInput("Company", label = "Company:",
            choices = c("Amazon","Apple", "Alphabet"),selected = c("Amazon"), multiple = TRUE)

sliderInput("timestamp", label = "Date to display:",
            min(combinedDF$timestamp), max(combinedDF$timestamp), 
            value = c(min(combinedDF$timestamp), max(combinedDF$timestamp)), 
            step = NULL)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Opening share price (ggplot)

```{r fig.width=17}

dataset <- reactive({
  combinedDF %>%
    filter(Company == input[['Company']])
})

renderPlot({
    ggplot(dataset(), aes(x = timestamp, y = open, colour = Company)) +
    geom_line() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    theme_bw() +
    xlab("Date") + ylab("Opening value") +
    theme(text = element_text(size=20))
})

```

### Opening share price (plotly)

```{r fig.width=15}

plot_ly(data = combinedDF, x = ~timestamp, y = ~open, color = ~Company, type = 'scatter', mode = 'lines') %>%
  layout(xaxis = list(title = 'Date', showline = TRUE), yaxis = list(title = 'Opening value', showline = TRUE))

```


